apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - name: pipeline
        image: lokesh220/pipeline:latest
        ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-service
spec:
  selector:
    app: pipeline
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 80
  type: NodePort  # Expose this service on a random port on each Node
